version: '3'

services:
  verdaccio:
    image: cr.yandex/crp3htsb576q3sp0eub8/verdaccio:dev
    restart: always
    ports:
      - '4873:4873'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - verdaccio-storage:/verdaccio/storage

volumes:
  verdaccio-storage:
